### ISSUE TITLE
With generator the argument names of method are not exposed on introspection

### ISSUE THREAD

**Issue by colazzo** [python-sdbus/python-sdbus#48] opened 2023-11-24 17:21 UTC
When generating code from this xml:
```
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node name="/sapv2s">
    <interface name="com.example.interface">
        <method name="Login">
            <arg name="UserName" direction="in" type="s"/>
            <arg name="PinCode" direction="in" type="s"/>
        </method>
    </interface>
</node>
```

I got this code:
```
class ComExampleInterfaceInterface(
    DbusInterfaceCommonAsync,
    interface_name="com.example.interface",
):
    @dbus_method_async(
        input_signature="ss",
    )
    async def login(
        self,
        user_name: str,
        pin_code: str,
    ) -> None:
        raise NotImplementedError
```

When doing Introspection on the Service it does not expose the argument names of the method as defined in the xml.

I know you can define the names with "input_args_names" but I would expect that the generator automatically fills in the argument names, or that the underlying implementation exposes the same names from the defined method by default when not custom defined.

Would this be possible to solve in the generator somehow? For example by having "input_args_names" populated with the names?

**Comment by igo95862** [comment] 2023-11-24 17:29
Hello @colazzo 

I will take a look at it.

Meanwhile can you try setting the `result_args_names` to an empty sequence?

```
    @dbus_method_async(
        input_signature="ss",
        result_args_names=(),
    )
```

**Comment by colazzo** [comment] 2023-11-24 21:47
Hi @igo95862, I did try it and does not change - also tried with `input_args_names=()` but the arguments are still without name.

**Comment by igo95862** [comment] 2023-11-25 08:17
I managed to add argument names to the introspection using following interface:

```python
class ComExampleInterfaceInterface(
    DbusInterfaceCommonAsync,
    interface_name="com.example.test",
):
    @dbus_method_async(
        input_signature="ss",
        result_signature="i",
        result_args_names=("result",)
    )
    async def login(
        self,
        user_name: str,
        pin_code: str,
    ) -> int:
        return 0
```

![Screenshot from 2023-11-25 14-09-35](https://github.com/python-sdbus/python-sdbus/assets/8576552/56c4b6e9-4287-4a27-b4dd-6d97e1ed59a5)

The issue is the current code is not smart enough to realize that a method without return values has an empty sequence of result argument names.

Originally the issue was that libsystemd has to have either all argument named or none. The input arguments names can be acquired from the python argument names, however, Python does not have a concept of the return argument names. So to utilize the input argument names the return names have to be provided. I think I will add some kind of default return argument names.

I will add a fix in the future version 0.12.0. Thank you for reporting this issue.

**Comment by colazzo** [comment] 2023-11-25 09:44
Good you found the root cause! Keep in mind that the 'case' of the argument names should be respected: when having defined "UserName" in the xml it should ideally also expose "UserName".

When would you plan to make version 0.12.0?

**Comment by igo95862** [comment] 2023-11-25 09:56
> Good you found the root cause! Keep in mind that the 'case' of the argument names should be respected: when having defined "UserName" in the xml it should ideally also expose "UserName".

It can be a simple to implement snake_case to CamelCase conversion.

> When would you plan to make version 0.12.0?

Not sure. I want to release a new version of [NetworkManager binds](https://github.com/python-sdbus/python-sdbus-networkmanager) first.

I will also fix the [`setter_private` not being available in overridden properties](https://github.com/python-sdbus/python-sdbus/discussions/47#discussioncomment-7454994).

**Comment by colazzo** [comment] 2023-11-25 12:17
Awesome!

**Comment by igo95862** [comment] 2023-12-28 15:46
So there are several issues at hand:

1. Impossible to annotate arguments with names for methods that don't have return values. This is because the empty tuple is currently used as default value therefore the default argument for argument names should be changed to None.
2. Should the argument names be exported to introspection when result names are passed and python arguments can be used for input names or should result names be auto-generated so that the argument names always get exported. 
3. Interface generator does not include the return argument names in to the generated classes even though it could. The "name" attribute is optional so interface generator should handle both if names are present and if they are not.
4. The D-Bus specification actually uses the snake_case for argument names. See: https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format So python argument probably could be simply re-used without conversion. I checked systemd and it uses the snake_case for argument names and so does NetworkManager.

**Comment by igo95862** [comment] 2023-12-29 15:53
I added 1708748db4b4eb43f6c50fd9acdf143aa4ec85e3 which now allows setting the argument names for methods that don't have return arguments.

This means:

```python
       class TestInterface(
            DbusInterfaceCommonAsync,
            interface_name="org.test.test",
        ):
            @dbus_method_async(
                input_signature="ss",
                result_args_names=(),
            )
            async def login(
                self,
                user_name: str,
                pin_code: str,
            ) -> None:
                return None
```

Will annotate the argument names in the introspection.

**Comment by igo95862** [comment] 2023-12-30 09:16
I think I will add some kind of option to the generator that indicates how to handle the argument names. For example, `preseve` would make generator preserve the argument names, `convert` which will convert argument names from CamelCase to snake_case. (like it does right now) There should also be some options on how `result_args_names` and `input_arg_names`. Maybe the default should be `result_args_names` always be set as Python provides no way to set the return argument names and `input_arg_names` would only be set if the original argument names are not in snake_case.

I checked the introspection files I have on my machine in `/usr/share/dbus-1/interfaces/` folder to see if it uses snake_case or CamelCase. It looks like Freedesktop and Systemd uses snake_case and KDE and Cannonical use lower camelCase. Since D-Bus specification does not actually state the case of argument names. So I don't see much reason to make the case conversion on by default.

By the way @colazzo is there a particular reason you want the argument names be accurately preserved? Are you sharing the introspection XML between multiple implementations?

**Comment by colazzo** [comment] 2023-12-30 09:28
If that is too complicated to have case preserved, then no need to add extra option or extra implementations. I can live with snake_case being exposed. It is just that in some other C++ lib implementation I was used to have the case preserved. The main issue here was actually no having the names at all for the method arguments, I think you already solved that right?

**Comment by igo95862** [comment] 2023-12-30 09:37
Yes. There are two ways to have the arguments named.

 First is only providing the result argument names with `result_args_names`. In this case the input argument names will be filled from python argument names.

Second is naming all the arguments manually by providing both  `result_args_names` and `input_args_names`.

If you make a mistake in for example number of arguments libsystemd will raise an error.

**Comment by colazzo** [comment] 2024-01-04 21:29
@igo95862  Sorry for late reply. If I understand correctly, it is still a manual action? Or has the generator been modified already for that? Let me know if you want me to verify something.

**Comment by igo95862** [comment] 2024-01-04 21:30
I have not modified the generator yet but it is on the TODO list.

**Comment by colazzo** [comment] 2024-01-18 08:00
@igo95862  Hello, something else I did notice which is also generator related:
Could it be that return of a signal method is wrong? When generating interface with a Signal the return type of the `@dbus_signal_async` method is always `None`. I would expect to have the `AsyncIterable` or something? 
Do you use mypy tool for static type checking?

**Comment by igo95862** [comment] 2024-01-18 08:46
Hello @colazzo 

It seems to be working fine for me. (both stable 0.11.1 and dev)

```
python -m sdbus gen-from-file /usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.xml | rg --after-context 5 signal

    @dbus_signal_async(
        signal_signature="u",
    )
    def state_changed(self) -> int:
        raise NotImplementedError

    @dbus_signal_async(
        signal_signature="o",
    )
    def device_added(self) -> str:
        raise NotImplementedError
```
The `-> type` indicates the typing of the signal.

**Comment by colazzo** [comment] 2024-01-18 10:16
Correct, in your example is returning the value of the signal argument, though I would expect for `state_changed` to have `AsyncIterable[int]` instead of returning `int` directly, as it is something that you need to iterate on to get the signal value. Or I am seeing this wrong?

**Comment by igo95862** [comment] 2024-01-18 10:22
The `dbus_signal_async` type is `Callable[[Callable[[Any], T]], DbusSignalAsync[T]]` so in case of `device_added` from example the type would be `DbusSignalAsync[str]`.

The `DbusSignalAsync[str]` would return `DbusSignalAsyncBaseBind[str]` which has the `async def catch(self) -> AsyncIterator[str]` method.

**Comment by igo95862** [comment] 2024-01-18 14:31
Basically the `@dbus_signal_async` + `def device_added(self) -> str:` is a syntaxic sugar. You can probably directly create the `DbusSignalAsync` attributes on the class.

**Comment by igo95862** [comment] 2024-02-25 10:58
I think I will postpone this to version 0.13. The current development version has a lot of changes and I want to release it sooner.

**Comment by colazzo** [comment] 2024-02-25 12:01
Fine for me.
When do you plan to release version 0.12 ?

**Comment by colazzo** [comment] 2024-03-17 09:42
Hi @igo95862, are you planning to make a RC version today? let me know if need some testing...

**Comment by igo95862** [comment] 2024-03-17 10:16
Hello @colazzo ,

Yes I am planning on releasing the RC version to PyPI today. It will be installable from PyPI but because it is RC version it can only be installed if the version is specified directly.

**Comment by igo95862** [comment] 2024-03-17 14:49
@colazzo It's uploaded now to PyPI: https://pypi.org/project/sdbus/0.12rc1/

However, I still need to write changelog.

**Comment by igo95862** [comment] 2024-03-17 15:42
Release is up as well as changelog: https://github.com/python-sdbus/python-sdbus/releases/tag/0.12.RC1

**Comment by igo95862** [comment] 2024-10-26 20:52
Added argument names to methods and signals in 7d7629169411c3837b38201cc2646b93092200c6.

**Closed** 2024-10-26 20:52 UTC
