### ISSUE TITLE
`request_default_bus_name_async` can fail silently

### ISSUE THREAD

**Issue by mswiger** [python-sdbus/python-sdbus#23] opened 2022-08-03 00:20 UTC
Hello! I have noticed that when calling `request_default_bus_name_async`, the method can fail without any indication that it failed. For example, if a name is requested and a service with that name already exists, then that name will not be reserved, but no error will be reported. It seems like this method should raise an exception or return some value indicating that it failed in cases like this (sd_bus_request_name does return an error code in this case unless the appropriate flags are set). What are your thoughts?

**Comment by igo95862** [comment] 2022-08-03 07:23
Hello,

It should raise an error but it does not currently. I need to investigate that.

Meanwhile the `request_default_bus_name` seems to be working correctly.

**Comment by igo95862** [comment] 2022-08-03 15:37
The issue is I did not read the specification documentation thoroughly.

The result of the name request is an integer where value of `1` represent and other values indicate a particular failure. I need to add the checks for a particular return value.

I will probably add a new exceptions that correspond to a particular return value as well as add new boolean flags to that will be translated in to the call flags. There is an undocumented `flags` parameter for the `request_default_bus_name_async` that I want to replace with boolean flags. Since it was undocumented I will completely remove it in `0.x.0` version without deprecation warning.

**Comment by mswiger** [comment] 2022-08-03 18:06
Understood, thanks for taking a look!

**Comment by igo95862** [comment] 2023-01-14 13:57
Should be fixed with a8bcbd217d7d92d8ab8872ec824f714d4715efd4 . Unit tests verify the behavior.

Now there are 3 different exceptions that will be raised depending on the flags.

**Closed by igo95862** 2023-01-14 13:57 UTC
