### ISSUE TITLE
Unable to get managed objects

### ISSUE THREAD

**Issue by IB1387** [python-sdbus/python-sdbus#11] opened 2022-04-12 09:42 UTC
I'm in search of a python dbus library with asyncio support, that also let's the user handle dbus signals with coroutines and python-sdbus looks promising. 
I'm however unable to get python-sdbus to do anything though:

python3 -m asyncio
```
import sdbus
om = sdbus.DbusObjectManagerInterfaceAsync.new_proxy("org.bluez", "/")
```
throws an exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/__main__.py", line 34, in callback
    coro = func()
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/sdbus/dbus_proxy_async.py", line 810, in new_proxy
    new_object._proxify(service_name, object_path, bus)
  File "/usr/local/lib/python3.9/dist-packages/sdbus/dbus_proxy_async.py", line 783, in _proxify
    self._attached_bus = bus if bus is not None else get_default_bus()
  File "/usr/local/lib/python3.9/dist-packages/sdbus/dbus_common.py", line 36, in get_default_bus
    new_bus = sd_bus_open()
sd_bus_internals.SdBusLibraryError: Line: 25. sd_bus_open(&(new_sd_bus->sd_bus_ref)) in function sd_bus_py_open returned error: 123
```

Also with the example_server.py and the example_client.py I get the same error when requesting the default bus name (server) or creating the proxy (client).

I'm running this on a raspberrypi with RaspberryPiOS Lite 64Bit (tried 64 bit as 32 bit didn't work with the same error).
Does anybody have an idea on what I'm doing wrong?

**Comment by igo95862** [comment] 2022-04-12 10:28
Error code 123 is ENOMEDIUM.

According to sd-bus manuals:

>  -ENOMEDIUM
>           The requested bus type is not available because of invalid
>           environment (for example the user session bus is not available
>           because $XDG_RUNTIME_DIR is not set).

Most likely you don't have D-Bus running.

**Comment by IB1387** [comment] 2022-04-12 10:38
Thanks a lot for the swift reply! I'm trying to use this on a head-less environment with SSH. I have non-async code successfully running using dasbus - so I think dbus should be running? I'm trying to implement a rather complex application using bluez.

**Comment by igo95862** [comment] 2022-04-12 11:00
Try opening the system bus explicitly

```python
import sdbus

system_bus = sdbus.sd_bus_open_system()
```

**Comment by IB1387** [comment] 2022-04-12 11:08
I tried that before, not completely understanding what I was doing:

```
root@test-pi:/home/pi# python3 -m asyncio
asyncio REPL 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import sdbus
>>> system_bus = sdbus.sd_bus_open_system()
>>> proxy = sdbus.DbusObjectManagerInterfaceAsync.new_proxy("org.bluez", "/", system_bus)
>>> await proxy.get_managed_objects()
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/sdbus/dbus_proxy_async.py", line 111, in _call_dbus_async
    reply_message = await interface._attached_bus.call_async(
sdbus.dbus_exceptions.DbusNoReplyError: Connection terminated
```

**Comment by igo95862** [comment] 2022-04-12 11:16
Try using a script file.

```python

import asyncio
import sdbus
system_bus = sdbus.sd_bus_open_system()
proxy = sdbus.DbusObjectManagerInterfaceAsync.new_proxy("org.bluez", "/", system_bus)
 
def test():
     print(await proxy.get_managed_objects())

asyncio.run(test())
```

**Comment by igo95862** [comment] 2022-04-12 11:19
I never tested against async REPL and it seems to be not functioning properly.

The sync REPL seems fine.

**Comment by IB1387** [comment] 2022-04-12 11:24
Oh wow, I tested it in a file, but without explicitly opening the system bus. Now outside of the REPL and with `sd_bus_open_system` it seems to work!

I'll need to implement some bluez interfaces and port my existing bluetooth stack from dasbus to sdbus now. Thanks a alot and wish me luck :-)

**Comment by igo95862** [comment] 2022-04-12 11:31
> I'll need to implement some bluez interfaces and port my existing bluetooth stack from dasbus to sdbus now.

The bluez interfaces are very widely requested.

I wanted to implement them but the issue is that there is no way to easily extract them. I opened an issue on bluez bug tracker but no response so far: https://github.com/bluez/bluez/issues/296

Maybe you can send me some XML dumps and I will start working on them. (also remmember there is a [code generator](https://python-sdbus.readthedocs.io/en/latest/code_generator.html))

**Comment by IB1387** [comment] 2022-04-12 11:44
I'll spend some time today to take a look at the work required to implement the adapter, device and gatt interfaces, which I need for my project, as I'm on a really tight deadline. For the interfaces I have access to, I can definitely send over the XML dumps.

**Comment by igo95862** [comment] 2022-04-12 18:13
Should I close this issue?

**Comment by IB1387** [comment] 2022-04-12 18:21
Yeah everything seems to be working!
How should I send you the introspection dumps and maybe even the generated Interface classes as well as the error classes I created?

**Comment by igo95862** [comment] 2022-04-12 19:57
> Yeah everything seems to be working! How should I send you the introspection dumps and maybe even the generated Interface classes as well as the error classes I created?

I opened an issue to collect introspection XML:

https://github.com/python-sdbus/python-sdbus-bluez/issues/1

**Closed** 2022-04-13 12:08 UTC
