### ISSUE TITLE
Service method fails with only tuple as argument

### ISSUE THREAD

**Issue by colazzo** [python-sdbus/python-sdbus#52] opened 2024-02-05 15:56 UTC
Hi,

I am trying to pass a tuple of integers into my service function as single argument but I can't get it work, don't know if I am missing something doing this?

        <method name="SetSystemDate">
            <arg name="date" type="(iiii)" direction="in">
            </arg>
        </method>

        <method name="SetSystemDate2">
            <arg name="id" type="s" direction="in"/>
            <arg name="date" type="(iiii)" direction="in">
            </arg>
        </method>

This generates following Python code:

    @dbus_method_async(
        input_signature="(iiii)",
    )
    async def set_system_date(
        self,
        date: Tuple[int, int, int, int],
    ) -> None:
        ...

    @dbus_method_async(
        input_signature="s(iiii)",
    )
    async def set_system_date2(
        self,
        id: str,
        date: Tuple[int, int, int, int],
    ) -> None:
        ...

Trying to call SetSystemDate function from a test client always fails with "DbusFailedError", further I don't have more info why exactly.

As a test I did add a second method SetSystemDate2 having as first argument a string (not a tuple), and second argument the same tuple as in first method, and that one seem to work fine.

Any idea if this is a known issue, or do I need to add something in the interface? 
Thanks

**Comment by igo95862** [comment] 2024-02-05 16:28
Hello @colazzo 

The issue is that tuple is both multiple arguments and as a structure. The python arguments return a tuple when they return multiple arguments. 

https://github.com/python-sdbus/python-sdbus/blob/540696b5ee6a2aef9dc3aaa2e74591a30b437c7a/src/sdbus/dbus_proxy_async_method.py#L160-L161

This is actually not the first issue because of this. See #10.
I guess I only fixed the returning of structures not the calling.

By the way why not use `iiii` as the input?

**Comment by igo95862** [comment] 2024-02-06 07:08
> avoid my python linting triggering a warning of too many arguments for that method

Let me guess, `pylint`?

> Is it feasible to fix that in next version?

Definitely. I already have a plan to change some internal APIs to fix this.

**Comment by igo95862** [comment] 2024-02-11 18:17
I made a commit 945dbee0c97ee3df903200e2ed6ac840cddf9f6a in the branch [replace-get-contents-with-parse-contents](https://github.com/python-sdbus/python-sdbus/tree/replace-get-contents-with-parse-contents) which should fix this issue. However, I am not entirely satisfied with it because it adds a lot of length checks.

What I think I will do is have two methods to parse message data. One will return data as Python would. Empty message would result None and a message with one complete type would return that complete type. This is how the current `get_contents()` works. The second method would always return the tuple to accurately represent the message structure. (this is how the method in that branch works) This would allow to fix the issues described in this issues.

**Comment by igo95862** [comment] 2024-02-18 10:54
Hello @colazzo ,

I implemented the new message method in the commit f58ace9ef9d57080dd03c47560cf81bb5b502fce. This should fix the methods that take a single struct. (and makes the D-Bus -> Python calls implementation simpler) Could you give it a test?

**Comment by igo95862** [comment] 2024-02-18 15:08
meson is only there for its `compile_commands.json` file so I can have the LSP running.

You should use the setuptools:

```
python setup.py build
```

**Comment by igo95862** [comment] 2024-02-18 15:13
But `SdBusSlot_close` was missing the second argument even though it was not used. Thank you for finding this. Hmm, I am wondering how much of the problem could that have caused.

**Comment by colazzo** [comment] 2024-02-18 18:30
@igo95862 got it built now and from my test it seems to be working fine!

Thank you,

**Comment by igo95862** [comment] 2024-02-18 18:39
Great! Should I close the issue?

**Comment by colazzo** [comment] 2024-02-18 18:48
Yes

**Closed** 2024-02-18 18:49 UTC
